<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Effort.EF6" Version="2.2.18" />
    <PackageReference Include="EntityFramework" Version="6.2.0" />
    <PackageReference Include="MSTest.TestAdapter" Version="4.3.2" />
    <PackageReference Include="MSTest.TestFramework" Version="4.3.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GerenciamentoFaturas.Application\GerenciamentoFaturas.Application.csproj" />
    <ProjectReference Include="..\GerenciamentoFaturas.Domain\GerenciamentoFaturas.Domain.csproj" />
    <ProjectReference Include="..\GerenciamentoFaturas.Infrastructure\GerenciamentoFaturas.Infrastructure.csproj" />
  </ItemGroup>

</Project>
